import express from 'express';
import { GoogleGenAI, Type } from '@google/genai';
import path from 'path';

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '50mb' }));

// Lazy-initialized server-side Gemini client
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

/**
 * POST /api/ai/analyze-image
 * Inspects image content to generate smart titles, tags, alt-text, and format recommendations.
 */
app.post('/api/ai/analyze-image', async (req, res) => {
  try {
    const { imageBase64, mimeType = 'image/png' } = req.body;
    if (!imageBase64) {
      return res.status(400).json({ error: 'Missing imageBase64 data' });
    }

    const ai = getGeminiClient();

    // Clean data URI prefix if present
    const cleanBase64 = imageBase64.replace(/^data:image\/[a-zA-Z0-9+.-]+;base64,/, '');

    const imagePart = {
      inlineData: {
        data: cleanBase64,
        mimeType: mimeType,
      },
    };

    const response = await ai.models.generateContent({
      model: 'gemini-3.7-flash',
      contents: {
        parts: [
          imagePart,
          {
            text: 'Analyze this image and return a concise, structured JSON object describing it for asset management, SEO alt-text, clean filename suggestion, and best web image format recommendation.',
          },
        ],
      },
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            suggestedFileName: {
              type: Type.STRING,
              description: 'A clean, slugified filename (no extension, lowercase with underscores).',
            },
            altText: {
              type: Type.STRING,
              description: 'Descriptive, accessible alt text for web accessibility.',
            },
            recommendedFormat: {
              type: Type.STRING,
              description: 'Best target format: png, webp, jpeg, avif, or svg.',
            },
            formatReason: {
              type: Type.STRING,
              description: 'Brief reason why this format is optimal (e.g. photos vs flat graphics).',
            },
            tags: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: '3-6 descriptive categorical tags.',
            },
            dominantColors: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: 'Hex color codes or descriptive names of primary colors.',
            },
          },
          required: ['suggestedFileName', 'altText', 'recommendedFormat', 'tags'],
        },
      },
    });

    const parsedJson = JSON.parse(response.text || '{}');
    res.json({ success: true, data: parsedJson });
  } catch (error) {
    console.error('AI Analysis Error:', error);
    res.status(500).json({
      success: false,
      error: 'Conversion not possible or AI analysis failed.',
      details: error instanceof Error ? error.message : String(error),
    });
  }
});

/**
 * POST /api/ai/edit-image
 * Generates an edited version of an image based on user text instructions.
 */
app.post('/api/ai/edit-image', async (req, res) => {
  try {
    const { imageBase64, mimeType = 'image/png', prompt } = req.body;
    if (!imageBase64 || !prompt) {
      return res.status(400).json({ error: 'Missing imageBase64 or prompt' });
    }

    const ai = getGeminiClient();
    const cleanBase64 = imageBase64.replace(/^data:image\/[a-zA-Z0-9+.-]+;base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-lite-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    let generatedImageUrl: string | null = null;
    let descriptionText = '';

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData?.data) {
          generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
        } else if (part.text) {
          descriptionText += part.text;
        }
      }
    }

    if (!generatedImageUrl) {
      return res.status(500).json({
        success: false,
        error: 'No edited image generated by the AI model.',
        text: descriptionText,
      });
    }

    res.json({
      success: true,
      imageUrl: generatedImageUrl,
      text: descriptionText,
    });
  } catch (error) {
    console.error('AI Edit Error:', error);
    res.status(500).json({
      success: false,
      error: 'AI image editing failed.',
      details: error instanceof Error ? error.message : String(error),
    });
  }
});